### ISSUE TITLE
Couldn't initialise framework "wdio-cucumber-framework".

### ISSUE THREAD

**Issue by shashikumarraja** [webdriverio/cucumber-boilerplate#125]
# Issue description
> Please provide a brief description of the problem you are experiencing
**Getting this error while running npm run wdio**
```
ERROR: Couldn't initialise framework "wdio-cucumber-framework".
Error: The module '/home/shashi/cucumber-boilerplate/node_modules/fibers/bin/linux-x64-57/fibers.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/shashi/cucumber-boilerplate/node_modules/fibers/fibers.js:24:37)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```
When checking my node version its **v8.1.2**
How to fix this

**Comment by wvankuipers** [comment]
Hello @shashikumarraja,

This seems to be an issue with the [fibers](https://github.com/laverdet/node-fibers) dependency and not directly related to the boilerplate. Please report this issue to them if it stil occurs.

**Comment by panzygoyal** [comment]
Hi

I am using wdio-cucumber-framework - 1.1.1 version and node - 10.15.1 . I am getting below issue while running my test cases. 

Starting Selenium Server
[13:01:47] spawn wdio with these attributes:
 /Users/XXXX/Desktop/XX/cuke-2019-02-21T13-01-47.415Z.tmp
## There is an issue with `node-fibers` ##
`/Users/XXXX/Desktop/XX/node_modules/wdio-cucumber-framework/node_modules/fibers/bin/darwin-x64-64/fibers.node` is missing.

Try running this to fix the issue: /Users/XXXX/.nvm/versions/node/v10.15.1/bin/node /Users/XXXX/Desktop/XX/node_modules/wdio-cucumber-framework/node_modules/fibers/build
Error: Cannot find module '/Users/XXXX/Desktop/XX/node_modules/wdio-cucumber-framework/node_modules/fibers/bin/darwin-x64-64/fibers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/XXXX/Desktop/XX/node_modules/wdio-cucumber-framework/node_modules/fibers/fibers.js:13:39)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/XXXX/Desktop/XX/node_modules/wdio-cucumber-framework/node_modules/fibers/future.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
ERROR: Couldn't initialise framework "wdio-cucumber-framework".
Error: Missing binary. See message above.
    at Object.<anonymous> (/Users/XXXX/Desktop/XX/node_modules/wdio-cucumber-framework/node_modules/fibers/fibers.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/XXXX/Desktop/XX/node_modules/wdio-cucumber-framework/node_modules/fibers/future.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by BruceChen1978** [comment]
I am running with node v10 and wdio-cucumber-framework v1.1.1, the experienced the same above error. How can I fix it?

**Comment by Angela0508** [comment]
I am running with node v18.16.1  I get the same above error. How can I fix it?
