### ISSUE TITLE
Tests don't run on chrome

### ISSUE THREAD

**Issue by krzywiecki** [webdriverio/cucumber-boilerplate#244]
# Issue description
Once I run tests using chrome, I have the following error:

```
yarn run v1.9.4
$ /var/workspace/automation-tests/node_modules/.bin/wdio
ERROR: An unknown server-side error occurred while processing the command. (UnknownError:undefined)
chrome
    at new RuntimeError (/var/workspace/automation-tests/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/var/workspace/automation-tests/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
    at Request.self.callback (/var/workspace/automation-tests/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/workspace/automation-tests/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/workspace/automation-tests/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

error Command failed with exit code 1.
```
I cloned the repo, all the setup is pretty much as default one, I changed only not relevant things. 
When I change browser do `firefox` in `wdio.conf.js` then it works fine so I suppose that it's maybe some problem with chrome driver? Could you please advise any good way of debugging?

# Expected behavior
Tests run as normal

# Actual behavior
Tests don't start on chrome

# Issue occurred on browser/platform 
Tested with Firefox and with chrome. The issue exists only on chrome.

# Additional info:
Chrome: Version 69.0.3497.100 (Official Build) (64-bit)
Node: v8.10.0
OS: Ubuntu 18.04.1 LTS

![image](https://user-images.githubusercontent.com/7432041/47644575-d880b800-db6e-11e8-9331-9a6d86731a55.png)

**Comment by christian-bromann** [comment]
@krzywiecki can you share your Chromedriver logs?

**Comment by krzywiecki** [comment]
@christian-bromann sorry for a silly question but where can I find the logs?

**Comment by christian-bromann** [comment]
@krzywiecki depending on how you run Chromedriver. You can paste in the stdout or use log command

**Comment by krzywiecki** [comment]
Could you please advise a bit, I'm a noob with all the configuration stuff. I have fresh, cloned boilerplate. I already ran: `yarn run clean` and `yarn install`. Then I'm trying to run ` yarn run wdio` and then have the error like above. Where should I log the chromedriver errors? Do I miss something?

**Comment by krzywiecki** [comment]
Ok, so seems that I didn't have a chromedriver installed at all. Shouldn't it be installed automatically once running `yarn install`? Also, I didn't have Java installed. I think it would be nice to mention in README about all pre-requirements.

**Comment by christian-bromann** [comment]
> Shouldn't it be installed automatically once running `yarn install`?

No

> I think it would be nice to mention in README about all pre-requirements.

Well setting up browser driver or even a grid is a whole different topic itself and can't be part of documenting this project. It assumes you have your test environment set up. I will add a note to the readme.
