### ISSUE TITLE
TypeError: Cannot read property 'tests' of undefined

### ISSUE THREAD

**Issue by ebuildy** [webdriverio/cucumber-boilerplate#59]
# Issue description
Got a nodeJS exception when running test

# Steps to reproduce
1) Clone project
2) npm install
3) Run an external selenium
4) Run web app
5) Run test: ``./node_modules/.bin/wdio --host localhost --port 4444``

# Expected behavior
This should work ^^

# Actual behavior
```
/Volumes/Data/tom/www/cucumber-boilerplate/node_modules/webdriverio/build/lib/utils/ReporterStats.js:318
            this.getSuiteStats(runner, runner.parent).tests[runner.title] = new TestStats(runner);
                                                     ^

TypeError: Cannot read property 'tests' of undefined
    at ReporterStats.testStart (/Volumes/Data/tom/www/cucumber-boilerplate/node_modules/webdriverio/build/lib/utils/ReporterStats.js:318:54)
    at BaseReporter.<anonymous> (/Volumes/Data/tom/www/cucumber-boilerplate/node_modules/webdriverio/build/lib/utils/BaseReporter.js:151:25)
    at emitOne (events.js:96:13)
    at BaseReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (/Volumes/Data/tom/www/cucumber-boilerplate/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)
    at Launcher.messageHandler (/Volumes/Data/tom/www/cucumber-boilerplate/node_modules/webdriverio/build/lib/launcher.js:594:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

# Issue occurred on browser/platform 
node v7.2.0

**Comment by webmagit** [comment]
Try updating to the latest webdriverio version. 
npm install webdriverio@latest --save 

Likewise the cucumber and wdio-cucumber-framework

**Comment by ebuildy** [comment]
Yep this does the trick!

Thanks you,

**Comment by kapilchokhawala** [comment]
I am still getting this error. 

```
/node_modules/webdriverio/build/lib/utils/ReporterStats.js:344
            this.getSuiteStats(runner, runner.parentUid || runner.parent).tests[ReporterStats.getIdentifi
er(runner)] = new TestStats(runner);
TypeError: Cannot read property 'tests' of undefined
```
This are the version of packages I have 
```
{
     "cucumber": "^5.0.2",
     "selenium-standalone": "^6.15.3",
    "wdio-cucumber-framework": "^2.2.7",
    "wdio-json-reporter": "^0.4.0",
    "wdio-multiple-cucumber-html-reporter": "^0.3.2",
    "wdio-selenium-standalone-service": "0.0.10",
    "webdriverio": "^4.14.0"
}
```

Anything that changed lately?? or solution to fix this?

**Comment by postmeback** [comment]
I am using Mocha..and the issue is pretty same like previous
